language: ruby
cache: bundler
rvm:
  - 2.7
  - 3.0
  - 3.1
script:
  - bundle install --path vendor/bundle
  - bundle exec rspec
  - gem build pokeapi_client.gemspec
  - gem install ./pokeapi_client-0.10.1-pre.0.gem
